### PR TITLE
QUICK EXTERMINATE THE RAT!

### PR DESCRIPTION
**Pull request by VMpc**
I came to laugh at how shit your code was and found your awfully hidden rat

### CODE REVIEW

**Comment by VMpc** [comment]
image

**Comment by efenatuyo** [comment]
You do know that that is used to check the key?

**Comment by efenatuyo** [comment]
That code isn’t even from me (don’t use it in my code)

**Comment by efenatuyo** [comment]
Before talking get a simple knowledge

**Comment by VMpc** [comment]
> That code isn’t even from me (don’t use it in my code)

yes you do (it's on your repl.it and it's the backend you try to hide)

**Comment by efenatuyo** [comment]
are you stupid or sum it uses a database (firebase) with saved **KEYS**. Then it checks if the given key in **BODY** is in the database. This code is not even from me

**Pull request closed without merging**
