### PR TITLE
bot visual remaster + extra commands

### PR DESCRIPTION
**Pull request by luluwaffless**
visually remastered the discord bot visuals and added 2 new commands: users and link
users simply returns the users in your room (if you're in one)
link returns the catalog link for an item in your queue based on position or ID
(also non-related but fixed some stuff in my theme and added the rooms stuff)
# images
- stats (in group) 
image
- stats (no group)
image
- queue 
image
- link
image
- users
image
- add/remove_id
image
- error messages
image
image
image
image
image

### CODE REVIEW

**Comment by efenatuyo** [comment]
Looks great

**Comment by efenatuyo** [comment]
I’ll take a look tmrw is 1 am for me

**Comment by luluontheweb** [comment]
> I’ll take a look tmrw is 1 am for me

alr!

**Review by efenatuyo — COMMENTED** [review]
everything looks great

**Comment by efenatuyo** [comment]
code will be merged into 12.0.0 branch

**Pull request closed without merging**
