### PR TITLE
added webhook support

### PR DESCRIPTION
**Pull request by luluwaffless**
added some code to make webhooks work back again, it should send it whenever a limited is successfully purchased
image

### CODE REVIEW

**Comment by efanetuyo** [comment]
hmm, great idea. In November we will start thinking about adding this feature. Good luck and keep using xolo

**Comment by efanetuyo** [comment]
We will add it in 6.1.0 actually, which will be released at 7pm CST

**Comment by efenatuyo** [comment]
> hmm, great idea. In November we will start thinking about adding this feature. Good luck and keep using xpöp

stop impersonating

**Comment by efanetuyo** [comment]
lol

**Comment by luluontheweb** [comment]
> lol

wtf

**Pull request merged**
