### PR TITLE
Fix your mistakes

### PR DESCRIPTION
**Pull request by VMpc**
🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 
This shit sucks, how do you make a sniper that's 600+ lines when all you need is a couple requests??
🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳 🇮🇳

### CODE REVIEW

**Comment by Enderspearl184** [comment]
TRUE

**Comment by efenatuyo** [comment]
because it is the different functions. I could make one 200 lines but wouldn't be as good as this one

**Comment by VMpc** [comment]
Yes, yes it would and it would be a shit ton better this code is hideous and slow.

**Comment by efenatuyo** [comment]
I already have a much better version (private) 200 lines but is not automated like this one.

**Comment by VMpc** [comment]
200 LINES FOR A SNIPER IN PYTHON STILL LMAO

**Pull request closed without merging**
