### PR TITLE
Nightfall Theme

### PR DESCRIPTION
**Pull request by luluwaffless**
this is my theme submittion for xolo's sniper! here's a little showcase:
image image
i remastered most of the text and optimized the print stuff by printing one single string and not multiple prints in the stats part, and also made it a little comfier for the eyes, giving it low-contrast colors, but yet making the stats and title stand-out a little

### CODE REVIEW

**Comment by db2dev** [comment]
thanks bro

**Review by dumbovita — COMMENTED** [review]
good

**Comment by efenatuyo** [comment]
could we not have the main name changed from xolo sniper to moon sniper. People know this as the xolo sniper so if a new name comes out meh

**Comment by luluontheweb** [comment]
> could we not have the main name changed from xolo sniper to moon sniper. People know this as the xolo sniper so if a new name comes out meh

ohh ok! i can change it if u want to, brb

**Comment by luluontheweb** [comment]
done! changed back to the old title, and also made an option in the `config.json` to make the title compact, just like the lower image, here's the new looks:
image image
now errors should appear red, ratelimits should appear yellow and buys should appear green, anything else will appear white

**Comment by luluontheweb** [comment]
outdated fork, updating soon

**Pull request closed without merging**
